# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e470bae5a8e1cce66275771f8c2985234fe5647c63db2a83aea449b44c82a93ab3c7b0a19febfd747cb92775262ccee4004d11885076d0aafb9e6fe0f34e16

test:
  secret_key_base: 4bbc7b031ffd0f10af5bb0647689547f02e90c069e088b07590f5316750cae482a13e03303744e9312e9d1aedf0ede8ababea6e5c09279a48eab88ca1016199d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
